#!/usr/bin/env ruby

$root = File.expand_path('../../../', __FILE__)
require "#{$root}/lib/acts_as_archive/gems"

ActsAsArchive::Gems.require(:spec_non_framework)

require 'active_support/dependencies'
require 'active_wrapper'

$db, $log, $mail = ActiveWrapper.setup(
  :base => "#{$root}/spec/fixtures",
  :env => 'test'
)
$db.establish_connection

ActiveSupport::Dependencies.autoload_paths << "#{$root}/spec/fixtures/helpers"
include SpecHelper

before_each true, false