require File.expand_path(File.dirname(__FILE__) + '/../lib/acts_as_archive/gems')
ActsAsArchive::Gems.require(:spec_rake)

require 'active_wrapper/tasks'

ActiveWrapper::Tasks.new(
  :base => File.dirname(__FILE__),
  :env => ENV['ENV']
)