require File.expand_path("#{File.dirname(__FILE__)}/../require")
Require.spec_rakefile!

begin
  ActiveWrapper::Tasks.new(
    :base => File.dirname(__FILE__),
    :env => ENV['ENV']
  )
rescue Exception
end